/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#ffb59e',
        'inverse-surface': '#e5e2e1',
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#20201f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'surface-variant': '#353535',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e6beb2',
        'inverse-on-surface': '#313030',
        'outline': '#ad897e',
        'outline-variant': '#5c4037',
        'primary': '#ffb59e',
        'primary-container': '#ff571a',
        'on-primary': '#5e1700',
        'on-primary-container': '#521300',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59e',
        'on-primary-fixed': '#3a0b00',
        'on-primary-fixed-variant': '#852400',
        'inverse-primary': '#ae3200',
        'secondary': '#ffdb9d',
        'secondary-container': '#feb700',
        'on-secondary': '#412d00',
        'on-secondary-container': '#6b4b00',
        'secondary-fixed': '#ffdea8',
        'secondary-fixed-dim': '#ffba20',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5e4200',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'card': '#252525',
      },
      fontFamily: {
        montserrat: ['Montserrat', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['6.4rem', { lineHeight: '7.2rem', letterSpacing: '-0.02em', fontWeight: '900' }],
        'headline-lg': ['4rem', { lineHeight: '4.8rem', letterSpacing: '-0.01em', fontWeight: '800' }],
        'headline-lg-mobile': ['3.2rem', { lineHeight: '3.8rem', fontWeight: '800' }],
        'headline-md': ['2.4rem', { lineHeight: '3.2rem', fontWeight: '700' }],
        'price-display': ['2.2rem', { lineHeight: '2.4rem', fontWeight: '700' }],
        'body-lg': ['1.8rem', { lineHeight: '2.8rem', fontWeight: '400' }],
        'body-md': ['1.6rem', { lineHeight: '2.4rem', fontWeight: '400' }],
        'label-md': ['1.4rem', { lineHeight: '2rem', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        'glow-active': '0 4px 20px rgba(255, 87, 26, 0.3)',
        'glow-card': '0 4px 20px rgba(255, 87, 26, 0.15)',
      },
    },
  },
  plugins: [],
}
